[package]
name = "gengar"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "gengar"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15" 
ethers = "2.0.14"
tokio = "1.38.0"
